site_name: core
site_description: CRM
repo_url: https://github.com/Akmaljon2002/taxiproject
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Akmaljon2002">Akmaljon2002</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
